In [1]:
import requests
import pandas as pd
import numpy as np
import time
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
import seaborn as sns
from selenium.webdriver.support import expected_conditions as EC
import matplotlib.pyplot as plt

In [16]:
url = "https://www.ceneo.pl/Pralki"
washing_mashine_links = []
s = Service('C:\webdrivers\chromedriver.exe')
driver = webdriver.Chrome(service=s)
driver.get(url)

WebDriverWait(driver, 30).until(EC.presence_of_element_located((By.XPATH, '//button[@class="cookie-consent__buttons__action js_cookie-consent-agree primary"]')))
cookies = driver.find_element(By.XPATH,'//button[@class="cookie-consent__buttons__action js_cookie-consent-agree primary"]')
cookies.click()
driver.refresh()

for page in range(1,38):
    scraped_links = driver.find_elements(By.XPATH,'//strong[@class="cat-prod-row__name"]//a[1]')
    for scraped_link in scraped_links:
        scraped_link = scraped_link.get_attribute('href')
        washing_mashine_links.append(scraped_link)
    if page != 37:
        next_page = driver.find_element(By.XPATH,'//a[@class="pagination__item pagination__next"]')
        next_page.click()
        print(f'Scraping product links from page {page}...')
    time.sleep(5)

Scraping product links from page 1...
Scraping product links from page 2...
Scraping product links from page 3...
Scraping product links from page 4...
Scraping product links from page 5...
Scraping product links from page 6...
Scraping product links from page 7...
Scraping product links from page 8...
Scraping product links from page 9...
Scraping product links from page 10...
Scraping product links from page 11...
Scraping product links from page 12...
Scraping product links from page 13...
Scraping product links from page 14...
Scraping product links from page 15...
Scraping product links from page 16...
Scraping product links from page 17...
Scraping product links from page 18...
Scraping product links from page 19...
Scraping product links from page 20...
Scraping product links from page 21...
Scraping product links from page 22...
Scraping product links from page 23...
Scraping product links from page 24...
Scraping product links from page 25...
Scraping product links from page 26...
Scraping product links from page 27...
Scraping product links from page 28...
Scraping product links from page 29...
Scraping product links from page 30...
Scraping product links from page 31...
Scraping product links from page 32...
Scraping product links from page 33...
Scraping product links from page 34...
Scraping product links from page 35...
Scraping product links from page 36...

In [23]:
washing_mashine_links = list(filter(lambda url: "Offer" not in url, washing_mashine_links))

In [24]:
washing_mashine_links[0:5]

['https://www.ceneo.pl/139782295###tag=nph_row_promotion',
 'https://www.ceneo.pl/90771474',
 'https://www.ceneo.pl/129065012',
 'https://www.ceneo.pl/156073012',
 'https://www.ceneo.pl/110631605']

In [25]:
all_data = []
for each_url in washing_mashine_links:
    driver.get(each_url)
    try:
        desc = driver.find_element(By.XPATH,'//div[@class="product-top__product-info__tags"]').text.strip()
    except:
        desc = np.nan
    try:
        name = driver.find_element(By.XPATH,'//div[@class="product-top__title"]').text.strip()
        print(f'Getting data about {name}...')
    except:
        name = np.nan
    try:
        score = driver.find_element(By.XPATH,'//span[@class="product-review__score"]').text.strip()
    except:
        score = np.nan
    try:
        number_reviews = driver.find_element(By.XPATH,'//span[@class="product-review__qo"]').text.strip()
    except:
        number_reviews = np.nan
    try:
        lowest_price = driver.find_element(By.XPATH,'//div[@class="product-offer-summary"]//span[@class="value"]').text.strip()
    except:
        lowest_price = np.nan
    try:
        free_delivery = driver.find_element(By.XPATH,'//div[@class="free-delivery-label"]').text.strip()
    except:
        free_delivery = np.nan
    all_data.append({"desc":desc,
                     "name":name,
                     "score":score,
                     "num_reviews":number_reviews,
                     "lowest_price":lowest_price,
                     "free_delivery":free_delivery})
    time.sleep(2)

In [26]:
pd.DataFrame(all_data)

     desc  name  score  num_reviews  lowest_price  free_delivery
0     NaN   NaN    NaN          NaN           NaN            NaN
1     NaN   NaN    NaN          NaN           NaN            NaN
2     NaN   NaN    NaN          NaN           NaN            NaN
3     NaN   NaN    NaN          NaN           NaN            NaN
4     NaN   NaN    NaN          NaN           NaN            NaN
..    ...   ...    ...          ...           ...            ...
969   NaN   NaN    NaN          NaN           NaN            NaN
970   NaN   NaN    NaN          NaN           NaN            NaN
971   NaN   NaN    NaN          NaN           NaN            NaN
972   NaN   NaN    NaN          NaN           NaN            NaN
973   NaN   NaN    NaN          NaN           NaN            NaN

[974 rows x 6 columns]